language: ruby
cache: bundler
gemfile: docs/Gemfile
script:
  - ALGOLIA_API_KEY='21d0b61fe8e19dff3bae7b819a12e84a' bundle exec jekyll algolia
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4